apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-fraud-ml-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-fraud-ml-api
  template:
    metadata:
      labels:
        app: secure-fraud-ml-api
    spec:
      containers:
        - name: secure-fraud-ml-api
          image: secure-fraud-ml-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "dev"
            - name: MODEL_PATH
              value: "model_artifacts/fraud_model.joblib"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: fraud-api-secret
                  key: API_KEY
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20