apiVersion: v1
kind: Service
metadata:
  name: secure-fraud-ml-api-service
spec:
  selector:
    app: secure-fraud-ml-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort